version: "3.7"

services: 
    backend:
        container_name: api
        image: node
        working_dir: /usr/src/app
        volumes: 
            - ./backend:/usr/src/app
        command: 
            npm start
        ports: 
            - 8002:3000
        networks: 
            - planner
    frontend:
        container_name: planner
        image: nginx
        volumes: 
            - ./frontend/:/usr/share/nginx/html:ro
        ports: 
            - 80:80
        networks: 
            - planner

networks: 
    planner:
        driver: bridge